# config context path to "/" by setting an empty string
server:
  contextPath:

google:
  client:
    clientId: 64984947785-lfq7ud2qd5rdrm5e57b156fdgkosjrh8.apps.googleusercontent.com
    clientSecret: w3p1zXrp4CYkzf8PHfPigvws
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope: email
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
    preferTokenInfo: true

facebook:
  client:
    clientId: 2263516557216793
    clientSecret: 02a0622136c1e955c1e19b52675ece6c
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: email

  resource:
    userInfoUri: https://graph.facebook.com/me?fields=name,email

github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    scope: user
  resource:
    userInfoUri: https://api.github.com/user
